name: loading_loading
description: Simple loading to your project.
version: 0.1.1
author: Flutterando Team <david@flutterando.com.br>
homepage: https://flutterando.com.br/
git: https://github.com/davidsdearaujo/loading_loading
repository: https://github.com/davidsdearaujo/loading_loading

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: